{
    "type": "bundle",
    "id": "bundle--82a7d325-2ecd-47f4-8851-6173a35ad778",
    "spec_version": "2.0",
    "objects": [
        {
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "source_ref": "malware--a19c1197-9414-46e3-986f-0f609ff4a46b",
            "target_ref": "attack-pattern--1c4e5d32-1fe9-4116-9d9d-59e3925bd6a2",
            "external_references": [
                {
                    "source_name": "CERT-FR PYSA April 2020",
                    "url": "https://www.cert.ssi.gouv.fr/uploads/CERTFR-2020-CTI-003.pdf",
                    "description": "CERT-FR. (2020, April 1). ATTACKS INVOLVING THE MESPINOZA/PYSA RANSOMWARE. Retrieved March 1, 2021."
                }
            ],
            "description": "[Pysa](https://attack.mitre.org/software/S0583) has executed a malicious executable by naming it svchost.exe.(Citation: CERT-FR PYSA April 2020)",
            "relationship_type": "uses",
            "id": "relationship--d77aa71a-e37f-4c8e-a4ad-b33a700afb7a",
            "type": "relationship",
            "modified": "2021-03-01T21:55:30.038Z",
            "created": "2021-03-01T21:55:30.038Z"
        }
    ]
}